org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens=java.base/java.lang=ALL-UNNAMED --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C\:/Program Files/Java/jdk-17
kotlin.daemon.enabled=false
kotlin.compiler.execution.strategy=in-process
